---

# - block:
#   - debug: var=elb_manage_elb_name
#   - debug: var=elb_manage_elb_subnets
#   - debug: var=elb_manage_elb_security_group_ids
#   - debug: var=elb_manage_elb_scheme
#   - debug: var=elb_manage_elb_listeners
#   - debug: var=elb_manage_elb_health_check
#   when: elb_manage_debug

- name: ensure ELB
  ec2_elb_lb:
    name:                   "{{ elb_manage_elb_name }}"
    state:                  present
    region:                 "{{ elb_manage_aws_region }}"
    scheme:                 "{{ elb_manage_elb_scheme }}"
    subnets:                "{{ elb_manage_elb_subnets }}"
    security_group_ids:     "{{ elb_manage_elb_security_group_ids }}"
    listeners:              "{{ elb_manage_elb_listeners }}"
    health_check:           "{{ elb_manage_elb_health_check }}"
  register: elb
